export interface ServiceFAQ {
  question: string
  answer: string
}

export interface ServiceDeliverable {
  name: string
  detail: string
}

export interface PricingTier {
  label: string
  price: string
  note?: string
}

export interface ServiceData {
  slug: string
  name: string
  category: string
  pitch: string
  priceFrom: string
  bookingUrl: string
  cardImage: string
  heroImage: string
  bullets: string[]
  whatItIs: string[]
  deliverables: ServiceDeliverable[]
  pricing: PricingTier[]
  pricingNote?: string
  whoFor: string[]
  resultStat: { label: string; value: string }
  faqs: ServiceFAQ[]
  seoTitle: string
  seoDescription: string
  featuredOnHome?: boolean
}

export const SERVICES: ServiceData[] = [
  {
    slug: 'user-acquisition',
    name: 'User Acquisition',
    category: 'GROWTH MARKETING',
    pitch: 'Precision-targeted campaigns that bring in users who actually activate, pay, and stay — not just those who click.',
    priceFrom: '₦400,000/month',
    bookingUrl: 'https://toptonmedia.com/apply',
    cardImage: 'https://images.unsplash.com/photo-1533750349088-cd871a92f312?w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1533750349088-cd871a92f312?w=1400&q=80',
    bullets: [
      'Google, Snapchat, Meta & TikTok install campaigns',
      'Audience segmentation & lookalike modelling',
      'Activation tracking from install to revenue',
    ],
    whatItIs: [
      'User acquisition is the practice of getting the right people to install, sign up for, or try your product — and then making sure they stick around. For Nigerian apps and digital products, that means running paid campaigns across Google, Meta, TikTok, and Snapchat with one goal: bring in users who become customers, not just numbers on a dashboard.',
      'We start by understanding what a valuable user looks like for your business — someone who completes onboarding, makes a first transaction, or hits whatever activation event matters most. Every campaign is built around finding more people who look like that.',
      'For African brands, this matters because ad costs are rising and budgets are tighter than ever. A campaign that drives cheap installs but no activations is a campaign that\u2019s quietly losing money. We track the full path from install to revenue so you always know what\u2019s actually working.',
    ],
    deliverables: [
      { name: 'Google App Campaigns (UAC)', detail: 'Automated campaigns across Search, Display, YouTube, and Discover targeting high-intent users.' },
      { name: 'Meta Install Campaigns', detail: 'Facebook and Instagram install campaigns built on activation-optimised audiences.' },
      { name: 'TikTok Install Campaigns', detail: 'Native-feeling creative built for TikTok\u2019s algorithm and audience behaviour.' },
      { name: 'Snapchat Advertising', detail: 'Reach younger, mobile-first audiences with formats built for the platform.' },
      { name: 'Audience segmentation & lookalike modelling', detail: 'Build lookalike audiences from your best existing users.' },
      { name: 'Creative testing (static, video, carousel)', detail: 'Continuous testing to find the creative that converts, not just the one that gets clicks.' },
      { name: 'Install tracking & attribution setup', detail: 'Proper MMP setup so every install is attributed to the right campaign and creative.' },
      { name: 'Post-install activation funnel strategy', detail: 'Onboarding and activation flow recommendations to turn installs into active users.' },
      { name: 'Retargeting for churned users', detail: 'Win back users who installed but went quiet.' },
      { name: 'Daily bid and budget optimisation', detail: 'Budgets shift toward what\u2019s working — every day, not once a month.' },
      { name: 'Weekly performance reports', detail: 'Clear weekly numbers: installs, cost per install, activation rate, and spend.' },
      { name: 'Monthly strategy reviews', detail: 'A monthly call to review what\u2019s working and plan the next sprint.' },
    ],
    pricing: [
      { label: 'Agency Fee', price: '₦400,000 – ₦2,000,000 / month', note: 'Ad spend billed separately. Minimum ₦200,000 ad budget recommended.' },
    ],
    whoFor: ['Fintech apps', 'E-commerce brands', 'SaaS startups'],
    resultStat: { label: 'Installs', value: '+85%' },
    faqs: [
      { question: 'What platforms do you run user acquisition campaigns on?', answer: 'We run campaigns across Google (UAC), Meta (Facebook & Instagram), TikTok, and Snapchat — choosing the mix based on where your target users actually spend time.' },
      { question: 'How long before we see results?', answer: 'Most accounts show meaningful install and cost data within the first 2 weeks. Activation and retention trends become clear by week 4–6, once we have enough data to optimise toward.' },
      { question: 'Do you handle the ad creative or do we provide it?', answer: 'We can do both. We typically produce and test new creative variants monthly, but if you have existing brand assets, we\u2019ll incorporate and test those alongside our own.' },
      { question: 'What tracking setup is required before we start?', answer: 'You\u2019ll need a mobile measurement partner (like AppsFlyer or Adjust) connected to your app, or we can help you set one up before launch — proper attribution is non-negotiable.' },
      { question: 'Can you work with a small daily budget?', answer: 'Yes, though we recommend a minimum of ₦200,000/month in ad spend to give the algorithms enough data to optimise effectively across platforms.' },
    ],
    seoTitle: 'User Acquisition Agency Lagos | App Growth — Topton Media',
    seoDescription: 'Topton Media runs precision-targeted user acquisition campaigns on Google, Meta, TikTok, and Snapchat for Nigerian apps and brands. Get users who activate and pay.',
    featuredOnHome: true,
  },
  {
    slug: 'lead-generation',
    name: 'Lead Generation',
    category: 'GROWTH MARKETING',
    pitch: 'High-intent leads for B2B and B2C brands, delivered into your CRM — not just your inbox.',
    priceFrom: '₦400,000/month',
    bookingUrl: 'https://toptonmedia.com/apply',
    cardImage: 'https://images.unsplash.com/photo-1432888622747-4eb9a8efeb07?w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1432888622747-4eb9a8efeb07?w=1400&q=80',
    bullets: [
      'Multi-channel lead capture (Meta, Google, LinkedIn)',
      'CRM integration and lead scoring',
      'Nurture sequences built to close',
    ],
    whatItIs: [
      'Lead generation is the system that turns strangers into people who\u2019ve raised their hand — they\u2019ve given you their contact details because they\u2019re interested in what you sell. For B2B and B2C brands across Nigeria, we build that system end-to-end: the ads that attract attention, the landing pages that capture details, and the CRM workflows that make sure no lead gets lost.',
      'The difference between a lead and a click is intent. A click costs you money. A lead is a person who has told you, in some form, that they want to talk. We design every campaign around capturing that intent — through forms, calculators, downloadable guides, or direct contact requests — and routing it straight into your sales process.',
      'For Nigerian businesses, the biggest leak isn\u2019t usually generating leads — it\u2019s what happens after. Leads sit in a spreadsheet, or an inbox, or a WhatsApp chat that nobody follows up on. We fix that by connecting lead capture directly to your CRM and building automated follow-up so leads get nurtured even when your team is busy.',
    ],
    deliverables: [
      { name: 'Lead capture campaign strategy', detail: 'Multi-channel strategy across Meta, Google, and LinkedIn tailored to your audience.' },
      { name: 'Custom landing page design', detail: 'Conversion-optimised landing pages built specifically for each campaign.' },
      { name: 'Lead magnet creation', detail: 'Guides, calculators, and tools that give people a reason to share their details.' },
      { name: 'CRM integration', detail: 'HubSpot, Zoho, or custom CRM setup so leads land where your team works.' },
      { name: 'Lead scoring setup', detail: 'Prioritise leads by likelihood to convert so sales focuses on the right people first.' },
      { name: 'Automated nurture email sequences', detail: 'Email flows that keep leads warm until they\u2019re ready to buy.' },
      { name: 'WhatsApp follow-up automation', detail: 'Automated WhatsApp messages for the channel Nigerian customers actually respond to.' },
      { name: 'Weekly lead quality reporting', detail: 'Not just lead volume — we report on quality and conversion potential.' },
      { name: 'A/B testing of forms and landing pages', detail: 'Continuous testing to lower cost per lead and raise form completion rates.' },
    ],
    pricing: [
      { label: 'Agency Fee', price: '₦400,000 – ₦2,000,000 / month' },
      { label: 'Landing Page Design', price: '₦200,000 – ₦600,000', note: 'One-off' },
    ],
    whoFor: ['B2B service businesses', 'Real estate developers', 'Education & training providers'],
    resultStat: { label: 'Lead Volume', value: '3x' },
    faqs: [
      { question: 'What counts as a "lead" in your reporting?', answer: 'Any contact who submits a form, requests a callback, or starts a conversation through a campaign-driven channel — with enough information for your sales team to follow up.' },
      { question: 'Do you guarantee a number of leads per month?', answer: 'We don\u2019t guarantee fixed numbers because results depend on budget, market, and offer — but we set realistic targets together based on your historical data and category benchmarks.' },
      { question: 'Can you work with our existing CRM?', answer: 'Yes — we\u2019ve integrated with HubSpot, Zoho, and several custom-built CRMs. If you\u2019re not using one yet, we can recommend and set one up.' },
      { question: 'What\u2019s the minimum commitment?', answer: 'We recommend a 3-month minimum so we have enough campaign data to optimise cost per lead and lead quality.' },
      { question: 'How do you handle WhatsApp follow-up?', answer: 'We set up automated WhatsApp sequences using approved business tooling, so leads get an immediate response even outside business hours.' },
    ],
    seoTitle: 'Lead Generation Agency Lagos | B2B & B2C Leads — Topton Media',
    seoDescription: 'Topton Media generates high-intent leads for B2B and B2C brands in Nigeria using paid media, landing pages, and CRM integration. Leads delivered, not just clicks.',
    featuredOnHome: true,
  },
  {
    slug: 'performance-marketing',
    name: 'Performance Marketing',
    category: 'GROWTH MARKETING',
    pitch: 'Full-funnel paid media measured exclusively on revenue outcomes, not vanity metrics.',
    priceFrom: '₦400,000/month',
    bookingUrl: 'https://toptonmedia.com/apply',
    cardImage: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1400&q=80',
    bullets: [
      'Campaign strategy & media planning',
      'Creative testing at scale',
      'Daily bid & budget optimisation',
    ],
    whatItIs: [
      'Performance marketing means every cedi, naira, or dollar of ad spend is tied to a measurable business outcome — a sale, a sign-up, a booking. It\u2019s the opposite of brand awareness campaigns where success is measured in impressions. We plan and run full-funnel paid media across Meta, Google, and TikTok with revenue as the only scoreboard that matters.',
      'This starts with media planning: deciding which platforms, audiences, and budgets give you the best shot at your specific goal. From there, we build out campaigns with proper conversion tracking from day one, so every shilling of spend can be traced back to whether it produced revenue.',
      'What makes this different from a typical "we\u2019ll run your ads" arrangement is the optimisation cadence. We adjust bids and budgets daily based on what\u2019s converting — not monthly, not when someone remembers to check. For brands competing in crowded categories, that daily attention is often the difference between a profitable channel and a money pit.',
    ],
    deliverables: [
      { name: 'Campaign strategy & media planning', detail: 'A clear plan for which platforms and budgets will hit your revenue targets.' },
      { name: 'Platform setup and account structure', detail: 'Properly structured ad accounts built for scale and clean reporting.' },
      { name: 'Creative testing at scale', detail: '5–10 new ad variants tested monthly to find what converts.' },
      { name: 'Daily bid & budget optimisation', detail: 'Spend shifts toward what\u2019s working, every single day.' },
      { name: 'Audience research and segmentation', detail: 'Identify and target the segments most likely to convert.' },
      { name: 'Cross-platform attribution', detail: 'Understand how channels work together across the customer journey.' },
      { name: 'A/B landing page testing', detail: 'Test landing page variants to improve conversion rate, not just click-through rate.' },
      { name: 'Bi-weekly performance calls', detail: 'Regular check-ins so you\u2019re never out of the loop on what\u2019s happening.' },
      { name: 'Monthly revenue impact reporting', detail: 'Reports built around revenue and ROAS, not impressions and reach.' },
    ],
    pricing: [
      { label: 'Agency Fee', price: '₦400,000 – ₦2,000,000 / month', note: 'Ad spend billed separately.' },
    ],
    whoFor: ['E-commerce brands', 'Subscription businesses', 'Service businesses with online booking'],
    resultStat: { label: 'Average ROAS', value: '4.2x' },
    faqs: [
      { question: 'How is performance marketing different from "regular" ads?', answer: 'Regular ad management often optimises for clicks or reach. Performance marketing optimises specifically for the revenue or conversion event you care about — and reports on that, not vanity metrics.' },
      { question: 'What\u2019s the minimum ad spend you recommend?', answer: 'It depends on your category, but generally we recommend at least ₦300,000–500,000/month in ad spend to give platforms enough volume to optimise effectively.' },
      { question: 'How often will I get reports?', answer: 'You\u2019ll get a monthly revenue impact report, plus bi-weekly calls to discuss performance and next steps in real time.' },
      { question: 'Can you work alongside our in-house marketing team?', answer: 'Yes — we frequently work as the paid media arm alongside in-house teams handling brand, content, or other channels.' },
      { question: 'What if a campaign isn\u2019t working?', answer: 'We kill or pivot underperforming campaigns quickly. Part of the daily optimisation process is recognising what isn\u2019t working and reallocating budget before it becomes a bigger loss.' },
    ],
    seoTitle: 'Performance Marketing Agency Lagos — Topton Media',
    seoDescription: 'Topton Media runs full-funnel paid media for brands in Nigeria — Meta, Google, TikTok — measured exclusively on revenue outcomes. No vanity metrics.',
    featuredOnHome: true,
  },
  {
    slug: 'web-design-cro',
    name: 'Web Design & CRO',
    category: 'TECH & WEB',
    pitch: 'Marketing websites built fast, designed sharp, and optimised to hold paid traffic and convert it into pipeline.',
    priceFrom: '₦200,000',
    bookingUrl: 'https://toptonmedia.com/apply',
    cardImage: 'https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=1400&q=80',
    bullets: [
      'Marketing site design & build',
      'CMS setup & team training',
      'Performance, Core Web Vitals & Analytics/GTM setup',
    ],
    whatItIs: [
      'Your website is often where paid traffic goes to die. CRO (conversion rate optimisation) and good web design exist to fix that — making sure that once someone clicks your ad, the site they land on actually convinces them to act. We design and build marketing websites with that single job in mind.',
      'This isn\u2019t just about looking good, although it should. It\u2019s about load speed, mobile experience, clear messaging hierarchy, and calls-to-action that are obvious and frictionless. A beautiful site that takes 6 seconds to load on mobile data is a site that\u2019s losing you customers before they even see your offer.',
      'We build on WordPress, Webflow, or custom code depending on your needs, set up proper analytics and tracking from day one, and train your team to make basic updates without needing a developer for every change.',
    ],
    deliverables: [
      { name: 'Marketing site design & development', detail: 'Custom-designed site built around your brand and conversion goals.' },
      { name: 'CMS setup', detail: 'WordPress, Webflow, or custom CMS — whichever fits your team best.' },
      { name: 'Team training on CMS', detail: 'Your team learns to update content without calling a developer.' },
      { name: 'Core Web Vitals optimisation', detail: 'Fast load times that keep both users and Google happy.' },
      { name: 'Google Analytics 4 setup', detail: 'Proper GA4 implementation so you can see what\u2019s actually happening.' },
      { name: 'Google Tag Manager (GTM) setup', detail: 'Flexible tracking setup that scales as your needs grow.' },
      { name: 'Conversion tracking & event setup', detail: 'Track the actions that matter — form fills, purchases, sign-ups.' },
      { name: 'SEO-ready site architecture', detail: 'Built with search visibility in mind from the ground up.' },
      { name: 'Mobile-first, responsive design', detail: 'Looks and works great on the devices your customers actually use.' },
      { name: 'Landing page variants for paid campaigns', detail: 'Dedicated landing pages built to match specific ad campaigns.' },
    ],
    pricing: [
      { label: 'Landing Page', price: '₦200,000 – ₦600,000', note: '1 week' },
      { label: 'Business Website (5–10 pages)', price: '₦800,000 – ₦3,000,000', note: '3–5 weeks' },
      { label: 'E-commerce Website', price: '₦1,500,000 – ₦6,000,000', note: '4–8 weeks' },
    ],
    whoFor: ['SMEs needing a first website', 'Brands relaunching their site', 'Companies running paid traffic to outdated pages'],
    resultStat: { label: 'Conversion Rate', value: '+41%' },
    faqs: [
      { question: 'How long does a typical website project take?', answer: 'A landing page takes about a week. A full business website typically takes 3–5 weeks, and e-commerce builds take 4–8 weeks depending on complexity.' },
      { question: 'Will I be able to update the site myself afterward?', answer: 'Yes — we set up a CMS appropriate for your team\u2019s technical comfort level and provide training so you can update text, images, and basic content yourself.' },
      { question: 'Do you redesign existing sites or only build new ones?', answer: 'Both. We frequently take over existing sites that are slow, outdated, or not converting, and rebuild them with the same content but better structure and performance.' },
      { question: 'Is hosting included?', answer: 'Hosting isn\u2019t included in the design fee, but we\u2019ll recommend reliable hosting options and can manage the setup for you.' },
      { question: 'What if I already have a logo and brand guidelines?', answer: 'Even better — we\u2019ll design within your existing brand system. If you don\u2019t have one yet, our Brand Strategy service can help.' },
    ],
    seoTitle: 'Web Design & CRO Agency Lagos — Topton Media',
    seoDescription: 'Topton Media builds fast, sharp marketing websites designed to convert paid traffic into leads and revenue. CMS setup, analytics, Core Web Vitals and GTM included.',
    featuredOnHome: true,
  },
  {
    slug: 'social-media-management',
    name: 'Social Media Management',
    category: 'GROWTH MARKETING',
    pitch: 'Content strategy and community management that builds brand trust without burning your team.',
    priceFrom: '₦300,000/month',
    bookingUrl: 'https://toptonmedia.com/apply',
    cardImage: 'https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=1400&q=80',
    bullets: [
      'Monthly content calendars',
      'Creative direction & production',
      'Community management',
    ],
    whatItIs: [
      'Social media management is the ongoing work of keeping your brand visible, consistent, and responsive across the platforms your audience actually uses. For most Nigerian brands, that means Instagram, Facebook, TikTok, and increasingly LinkedIn and X — each with different content needs and audience expectations.',
      'We plan a month of content at a time, built around themes that connect to your business goals — not just "post something every day." Every piece of content has a job, whether that\u2019s building trust, driving engagement, or supporting a campaign running elsewhere.',
      'The other half of the job is community management — responding to comments, DMs, and mentions in your brand voice, consistently. This is where a lot of brands fall down: posting great content but going silent when people engage with it. We handle both sides so your social presence feels alive.',
    ],
    deliverables: [
      { name: 'Monthly content calendar', detail: '30+ posts per month planned around your goals and key dates.' },
      { name: 'Creative direction & content production', detail: 'Visual direction and asset production for every post.' },
      { name: 'Copywriting & captions', detail: 'On-brand copy written for each platform\u2019s audience and format.' },
      { name: 'Scheduling & publishing', detail: 'Content goes out on time, every time, across all platforms.' },
      { name: 'Community management', detail: 'Comments, DMs, and mentions handled in your brand voice.' },
      { name: 'Hashtag & SEO research', detail: 'Discoverability research so content reaches beyond your existing followers.' },
      { name: 'Monthly analytics report', detail: 'Clear reporting on what\u2019s working and what to adjust.' },
    ],
    pricing: [
      { label: 'Social Media Management', price: '₦300,000 – ₦1,500,000 / month', note: '2–4 platforms' },
    ],
    whoFor: ['Restaurants & hospitality brands', 'Retail & e-commerce', 'Professional services'],
    resultStat: { label: 'Content Output', value: '30+ posts/mo' },
    faqs: [
      { question: 'Which platforms do you manage?', answer: 'Most commonly Instagram, Facebook, TikTok, LinkedIn, and X. We recommend 2–4 platforms based on where your audience is most active.' },
      { question: 'Do you create the content or do we need to provide assets?', answer: 'We handle content production, but if you have product photography, videos, or brand assets, we\u2019ll incorporate those into the calendar.' },
      { question: 'How do you handle community management outside business hours?', answer: 'We set expectations on response windows upfront and monitor key channels during extended hours, with escalation paths for anything urgent.' },
      { question: 'Can social media management work alongside paid ads?', answer: 'Yes — in fact it works best that way. Organic content builds the brand trust that makes paid ads convert better.' },
      { question: 'What\u2019s the minimum commitment?', answer: 'We recommend a 3-month minimum so content and community management can build momentum and show measurable growth.' },
    ],
    seoTitle: 'Social Media Management Agency Lagos — Topton Media',
    seoDescription: 'Topton Media manages social media for brands across Nigeria — content calendars, creative direction, posting, and community management on 2–4 platforms.',
    featuredOnHome: true,
  },
  {
    slug: 'pr-communications',
    name: 'PR & Communications',
    category: 'PR & COMMS',
    pitch: 'Strategic media relations, executive profiling, and crisis management that shapes how your brand is seen.',
    priceFrom: '₦500,000/month',
    bookingUrl: 'https://toptonmedia.com/apply',
    cardImage: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=1400&q=80',
    bullets: [
      'PR retainer & media placements',
      'Press releases & editorial distribution',
      'Executive profiling & personal brand',
    ],
    whatItIs: [
      'PR and communications is how your brand shows up in places you don\u2019t directly control — news coverage, industry features, executive interviews, and public conversation. Done well, it builds the kind of credibility that paid ads can\u2019t buy.',
      'We work as your media relations function: building relationships with journalists and editors, pitching stories, writing press releases, and securing placements that put your brand and leadership in front of the right audiences.',
      'For founders and executives, we also build personal brand presence — particularly on LinkedIn — so leadership becomes a recognisable, credible voice in your industry. And when things go wrong, we\u2019re ready with crisis communications support to manage the narrative quickly and clearly.',
    ],
    deliverables: [
      { name: 'PR retainer', detail: 'Ongoing media relations and placement tracking.' },
      { name: 'Press release writing & distribution', detail: 'Professionally written releases distributed to relevant outlets.' },
      { name: 'Media list management', detail: 'Curated relationships with journalists and editors relevant to your industry.' },
      { name: 'Executive profiling & LinkedIn thought leadership', detail: 'Build your leadership team\u2019s presence and credibility online.' },
      { name: 'Speaking opportunity placement', detail: 'Get your executives on stages and panels that matter.' },
      { name: 'Crisis communications & rapid response', detail: 'Fast, clear messaging when something goes wrong.' },
      { name: 'Stakeholder messaging', detail: 'Consistent messaging for investors, partners, and employees.' },
    ],
    pricing: [
      { label: 'PR Retainer', price: '₦500,000 – ₦2,000,000 / month', note: 'Minimum 3 months' },
      { label: 'Single Press Release', price: '₦100,000 – ₦300,000', note: '48–72 hours' },
      { label: 'Executive Profiling', price: '₦400,000 – ₦1,500,000 / month' },
      { label: 'Crisis Communications', price: '₦1,000,000 – ₦5,000,000' },
    ],
    whoFor: ['Fintechs & startups raising profile', 'Founders building personal brand', 'Companies navigating sensitive announcements'],
    resultStat: { label: 'Media Placements', value: 'Monthly' },
    faqs: [
      { question: 'Can you guarantee press coverage?', answer: 'No agency can guarantee coverage — but we can guarantee a consistent pitching process, strong media relationships, and stories worth covering. Placements follow from doing that work consistently.' },
      { question: 'Do you handle social media as part of PR?', answer: 'Executive thought leadership content (especially LinkedIn) is part of our PR offering. Broader brand social media is handled under our Social Media Management service.' },
      { question: 'How fast can you respond to a crisis?', answer: 'Crisis communications support typically begins within hours of being briefed — messaging and response plans are prioritised immediately.' },
      { question: 'What industries do you have media relationships in?', answer: 'Strongest relationships are in fintech, startups, business, and lifestyle media across Nigeria, with growing reach into regional and international outlets.' },
      { question: 'Is press release distribution included in the retainer?', answer: 'Yes, press release writing and distribution is included as part of an ongoing PR retainer; standalone releases are also available.' },
    ],
    seoTitle: 'PR Agency Lagos | Media Relations & PR — Topton Media',
    seoDescription: 'Topton Media provides PR and communications services in Lagos — media relations, press releases, executive profiling, and crisis communications for Nigerian brands.',
  },
  {
    slug: 'market-activations',
    name: 'Market Activations',
    category: 'ACTIVATIONS',
    pitch: 'On-ground brand experiences, product launches, and event executions that get people talking — and buying.',
    priceFrom: '₦500,000/project',
    bookingUrl: 'https://toptonmedia.com/apply',
    cardImage: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=1400&q=80',
    bullets: [
      'Event concept & production management',
      'Brand activation strategy',
      'Logistics, staffing & on-site management',
    ],
    whatItIs: [
      'Market activations are real-world events designed to put your brand directly in front of customers — product launches, pop-ups, experiential campaigns, and sponsored events. They work because they create a moment people remember and talk about, online and offline.',
      'We handle activations end-to-end: from the initial concept and strategy, through venue selection, logistics, staffing, and the actual on-site execution. The goal is always tied back to a business outcome — sales, sign-ups, brand awareness in a specific market, or a successful product launch.',
      'For brands entering new markets or launching new products in Nigeria, a well-executed activation can do in a day what months of digital campaigns might take to achieve — generating buzz, content, and direct customer feedback all at once.',
    ],
    deliverables: [
      { name: 'Brand activation concept & strategy', detail: 'A concept built around your launch or marketing goal.' },
      { name: 'Event production management', detail: 'Full project management from planning to execution.' },
      { name: 'Venue & logistics coordination', detail: 'Sourcing and managing every logistical detail.' },
      { name: 'Staffing & on-site management', detail: 'Trained staff and on-the-ground management on event day.' },
      { name: 'On-ground experiential marketing', detail: 'Interactive experiences that get people engaging with your brand.' },
      { name: 'Live social media coverage', detail: 'Real-time content capture and posting during the event.' },
      { name: 'Post-event reporting & impact analysis', detail: 'Clear reporting on attendance, engagement, and outcomes.' },
      { name: 'Print & branded merchandise coordination', detail: 'Signage, banners, and giveaways handled alongside printing and gifting services.' },
    ],
    pricing: [
      { label: 'Market Activation', price: '₦500,000 – ₦10,000,000+', note: 'Project-based' },
    ],
    whoFor: ['Product launches', 'International brands entering Nigeria', 'Retail & FMCG brands'],
    resultStat: { label: 'Brands Launched', value: '40+' },
    faqs: [
      { question: 'How far in advance should we plan an activation?', answer: 'For most activations, 4–6 weeks of lead time gives enough room for concept, logistics, and staffing. Larger launches may need 8–12 weeks.' },
      { question: 'Do you handle venue sourcing?', answer: 'Yes — we source and manage venue relationships as part of the logistics coordination.' },
      { question: 'Can you produce branded materials for the event?', answer: 'Yes, working alongside our Printing and Branded Gifts services for signage, banners, giveaways, and merchandise.' },
      { question: 'What\u2019s included in post-event reporting?', answer: 'Attendance numbers, engagement metrics, social media reach from the event, and a summary of outcomes against your original goals.' },
      { question: 'Do you work outside Lagos?', answer: 'Yes — we manage activations across Nigeria and can coordinate logistics for events in other African markets.' },
    ],
    seoTitle: 'Brand Activation & Event Marketing Agency Lagos — Topton Media',
    seoDescription: 'Topton Media plans and executes brand activations, product launches, and live marketing events across Lagos and Nigeria. Strategy, production, and on-site management.',
  },
  {
    slug: 'printing-services',
    name: 'Printing Services',
    category: 'PRINTING',
    pitch: 'End-to-end print services for brands — from stationery to outdoor signage. Design, print, and delivery.',
    priceFrom: '₦15,000',
    bookingUrl: 'https://toptonmedia.com/apply',
    cardImage: 'https://images.unsplash.com/photo-1562564055-71e051d33c19?w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1562564055-71e051d33c19?w=1400&q=80',
    bullets: [
      'Corporate stationery (cards, letterheads, folders)',
      'Marketing print (flyers, brochures, roll-up banners)',
      'Event & occasion print (programmes, invitations, backdrops)',
    ],
    whatItIs: [
      'Despite everything going digital, print still matters — business cards still get exchanged, banners still bring people into events, and a well-designed brochure still closes deals. We provide end-to-end printing services for Nigerian businesses and individuals: design, print, and delivery, handled by one team.',
      'Corporate clients use us for stationery (business cards, letterheads, folders, ID cards), marketing materials (flyers, brochures, roll-up and outdoor banners), and event print (programmes, invitations, backdrops, certificates). Individuals use us for everything from CVs to canvas prints and custom merchandise.',
      'Because we handle design alongside print, everything stays consistent with your brand — no back-and-forth between a designer and a separate printer. And because we manage production directly, we can offer faster turnaround and better pricing on bulk orders.',
    ],
    deliverables: [
      { name: 'Business Cards', detail: 'From ₦15,000 per 100 pieces, premium finishes available.' },
      { name: 'Letterheads', detail: 'From ₦25,000 per 100 pieces.' },
      { name: 'Compliment Slips, Envelopes & Folders', detail: 'Full corporate stationery suites designed to match your brand.' },
      { name: 'ID / Staff Cards', detail: 'Durable printed and laminated staff identification.' },
      { name: 'Flyers, Brochures & Company Profiles', detail: 'A5/A4 marketing materials for campaigns and pitches.' },
      { name: 'Roll-up Banners', detail: 'From ₦30,000 including stand.' },
      { name: 'Outdoor / Flex Banners', detail: 'From ₦8,000 per square metre.' },
      { name: 'Posters, Stickers & Branded Tote Bags', detail: 'Flexible print runs for promotions and giveaways.' },
      { name: 'Event Programmes & Invitations', detail: 'Programmes from ₦40,000/50pcs, invitations from ₦50,000/25pcs.' },
      { name: 'Certificates, Backdrops & Name Badges', detail: 'Everything needed for a polished event.' },
    ],
    pricing: [
      { label: 'Business Cards', price: 'From ₦15,000 / 100 pcs' },
      { label: 'Roll-up Banners', price: 'From ₦30,000 (incl. stand)' },
      { label: 'Outdoor / Flex Banners', price: 'From ₦8,000 / sqm' },
      { label: 'Event Programmes', price: 'From ₦40,000 / 50 pcs' },
      { label: 'Invitations', price: 'From ₦50,000 / 25 pcs' },
    ],
    pricingNote: 'Rush printing (24–48 hrs): +30%. Lagos delivery free above ₦100,000. Bulk discount: 10% off above ₦500,000.',
    whoFor: ['SMEs & corporates', 'Event planners', 'Individuals & personal projects'],
    resultStat: { label: 'Turnaround', value: '24–48 hrs' },
    faqs: [
      { question: 'Do you offer design services or just printing?', answer: 'Both — we design and print, so everything stays consistent and you don\u2019t need to coordinate between separate teams.' },
      { question: 'What\u2019s your turnaround time?', answer: 'Standard turnaround varies by product, typically 3–5 working days. Rush printing (24–48 hours) is available for a 30% surcharge.' },
      { question: 'Do you deliver outside Lagos?', answer: 'Yes, we deliver nationwide. Delivery within Lagos is free for orders above ₦100,000.' },
      { question: 'Is there a minimum order quantity?', answer: 'Minimums vary by product — most stationery items have minimums around 100 pieces, while banners and signage are typically per-item.' },
      { question: 'Do you offer bulk discounts?', answer: 'Yes — orders above ₦500,000 receive a 10% bulk discount.' },
    ],
    seoTitle: 'Printing Services Lagos | Corporate & Personal Printing — Topton Media',
    seoDescription: 'Topton Media offers end-to-end printing in Lagos — business cards, flyers, brochures, banners, event backdrops, invitations, and more. Design included. Fast turnaround.',
  },
  {
    slug: 'branded-gifts',
    name: 'Branded Corporate Gifts',
    category: 'GIFTING',
    pitch: 'High-quality branded gifts for staff, clients, and events — sourced, branded, packaged, and delivered by us.',
    priceFrom: '₦8,000/unit',
    bookingUrl: 'https://toptonmedia.com/apply',
    cardImage: 'https://images.unsplash.com/photo-1512909006721-3d6018887383?w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1512909006721-3d6018887383?w=1400&q=80',
    bullets: [
      'Welcome & onboarding gift packs',
      'Executive VIP gift sets',
      'Seasonal hampers & event giveaways',
    ],
    whatItIs: [
      'Branded corporate gifts are physical touchpoints — items that put your brand in someone\u2019s hands and, ideally, in their daily life. Done well, they say something about your brand\u2019s quality and attention to detail. Done badly, they end up in a drawer.',
      'We handle the full process: sourcing quality items, branding them properly (not just slapping a logo on), packaging them well, and delivering on time. Whether it\u2019s onboarding kits for new hires, VIP gifts for top clients, or giveaways for an event, we manage it as one project rather than a list of vendors.',
      'Because we work directly with suppliers and manage branding in-house where possible, we can offer better pricing on bulk orders and more control over quality — which matters when the gift is representing your brand.',
    ],
    deliverables: [
      { name: 'Welcome / Onboarding Pack', detail: '₦15,000 – ₦45,000 per pack, minimum order 10.' },
      { name: 'Executive VIP Gift Set', detail: '₦50,000 – ₦150,000 per set, minimum order 5.' },
      { name: 'Event Giveaway Pack', detail: '₦8,000 – ₦25,000 per pack, minimum order 25.' },
      { name: 'Seasonal Holiday Hamper', detail: '₦20,000 – ₦80,000 per hamper, minimum order 10.' },
      { name: 'Mugs & Drinkware', detail: 'Mugs ₦5,000–₦12,000, tumblers ₦10,000–₦30,000.' },
      { name: 'Premium Pens & Notebooks', detail: 'Pens ₦4,000–₦20,000, leather notebooks ₦12,000–₦40,000.' },
      { name: 'Apparel', detail: 'T-shirts ₦10,000–₦28,000, hoodies ₦25,000–₦65,000.' },
      { name: 'Tech Gifts', detail: 'Power banks ₦15,000–₦50,000, Bluetooth speakers ₦25,000–₦80,000.' },
    ],
    pricing: [
      { label: 'Welcome / Onboarding Pack', price: '₦15,000 – ₦45,000 / pack', note: 'MOQ: 10' },
      { label: 'Executive VIP Gift Set', price: '₦50,000 – ₦150,000 / set', note: 'MOQ: 5' },
      { label: 'Event Giveaway Pack', price: '₦8,000 – ₦25,000 / pack', note: 'MOQ: 25' },
      { label: 'Seasonal Holiday Hamper', price: '₦20,000 – ₦80,000 / hamper', note: 'MOQ: 10' },
    ],
    pricingNote: '70% deposit required before production. Standard lead time: 7–14 working days; rush (3–5 days) +35%. Bulk discounts: 10% (50+ units), 15% (100+), 20% (250+).',
    whoFor: ['HR & people teams', 'Executive offices', 'Event organisers'],
    resultStat: { label: 'Lead Time', value: '7–14 days' },
    faqs: [
      { question: 'What\u2019s the minimum order for branded gifts?', answer: 'Minimums vary by product — onboarding packs start at 10 units, event giveaways at 25, and VIP sets at 5.' },
      { question: 'Can I mix different items in one order?', answer: 'Yes, we frequently build custom packs combining multiple item types — this is common for onboarding kits and hampers.' },
      { question: 'How does payment work?', answer: 'We require a 70% deposit before production begins, with the balance due before delivery.' },
      { question: 'Can you rush an order for an upcoming event?', answer: 'Yes — rush production (3–5 days) is available for a 35% surcharge, subject to item availability.' },
      { question: 'Do you offer samples before a bulk order?', answer: 'For larger orders, we can arrange samples of branding and item quality before committing to the full production run.' },
    ],
    seoTitle: 'Corporate Branded Gifts Lagos — Topton Media',
    seoDescription: 'Topton Media creates branded corporate gifts in Lagos — onboarding packs, executive sets, event giveaways, and seasonal hampers. Sourced, branded, packaged, and delivered.',
  },
  {
    slug: 'brand-strategy',
    name: 'Brand Strategy & Creative',
    category: 'BRAND & CREATIVE',
    pitch: 'Brand identity, positioning, and creative campaigns built to make your brand unmistakable in any market.',
    priceFrom: '₦400,000',
    bookingUrl: 'https://toptonmedia.com/apply',
    cardImage: 'https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=1400&q=80',
    bullets: [
      'Brand identity (logo, colour, typography, guidelines)',
      'Full brand strategy & brand book',
      'Creative campaigns for launches and events',
    ],
    whatItIs: [
      'Brand strategy is the thinking behind how your business looks, sounds, and is positioned in the market — and brand identity is how that thinking gets expressed visually. Together they\u2019re the foundation everything else builds on: your website, your ads, your social content, even your gifts and print materials.',
      'We start with positioning — who you serve, what makes you different, and how you want to be perceived. From there, we build out visual identity: logo, colour palette, typography, and a usage guideline document that keeps everything consistent as your team and agency partners create new materials.',
      'For brands that already have an identity but it feels outdated or inconsistent, we offer rebrands — refreshing the visual system while preserving brand equity you\u2019ve already built. And for launches or campaigns, we develop creative concepts that bring the brand to life in a specific moment.',
    ],
    deliverables: [
      { name: 'Brand Identity', detail: 'Logo, colour palette, typography, and full brand guidelines.' },
      { name: 'Full Brand Strategy', detail: 'Positioning, messaging, tone of voice, and brand book.' },
      { name: 'Rebrand', detail: 'Refresh an existing identity while preserving brand equity.' },
      { name: 'Content Strategy', detail: 'A framework for how your brand shows up in content across channels.' },
      { name: 'Creative Campaigns', detail: 'Concept and creative development for launches and key moments.' },
    ],
    pricing: [
      { label: 'Brand Identity (logo + guidelines)', price: '₦400,000 – ₦2,000,000', note: '2–3 weeks' },
      { label: 'Full Brand Strategy', price: '₦1,000,000 – ₦5,000,000', note: '4–6 weeks' },
      { label: 'Rebrand', price: '₦800,000 – ₦4,000,000', note: '3–5 weeks' },
      { label: 'Content Strategy', price: '₦300,000 – ₦1,200,000', note: '2 weeks' },
      { label: 'Creative Campaigns', price: '₦500,000 – ₦3,000,000', note: '2–4 weeks' },
    ],
    whoFor: ['New businesses launching', 'Companies rebranding', 'Brands launching new products or campaigns'],
    resultStat: { label: 'Brands Identities Built', value: '40+' },
    faqs: [
      { question: 'What\u2019s the difference between brand identity and full brand strategy?', answer: 'Brand identity covers the visual system — logo, colours, typography, guidelines. Full brand strategy includes that plus positioning, messaging, tone of voice, and a complete brand book.' },
      { question: 'How long does a brand identity project take?', answer: 'Typically 2–3 weeks for a brand identity project, depending on the number of revision rounds.' },
      { question: 'Do you provide print-ready files?', answer: 'Yes, all final assets are delivered in formats ready for both digital use and print production.' },
      { question: 'Can you work with an existing logo we want to keep?', answer: 'Yes — in rebrand projects, we often preserve key elements of an existing identity while refreshing the overall system.' },
      { question: 'Do you also design the website and marketing materials?', answer: 'Yes, once the brand identity is set, we can extend it into web design (via our Web Design & CRO service) and print materials (via Printing Services).' },
    ],
    seoTitle: 'Brand Strategy & Identity Agency Lagos — Topton Media',
    seoDescription: 'Topton Media builds brand identities and creative campaigns for Nigerian brands — logo, brand guidelines, tone of voice, positioning, and launch creative.',
  },
  {
    slug: 'media-production',
    name: 'Media Production',
    category: 'PRODUCTION',
    pitch: 'Brand films, product photography, and social content — produced at a standard that actually performs.',
    priceFrom: '₦150,000',
    bookingUrl: 'https://toptonmedia.com/apply',
    cardImage: 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=1400&q=80',
    bullets: [
      'Brand films & corporate videos',
      'Product & event photography',
      '2D/motion graphics & animation',
    ],
    whatItIs: [
      'Media production covers everything that needs a camera, a microphone, or a render — brand films, product photography, social content shoots, podcasts, and motion graphics. The goal isn\u2019t just to produce content that looks good, but content that performs once it\u2019s out in the world.',
      'For brand films and corporate videos, we handle the full process from script to final delivery — concept, shoot, edit, and sound. For product and event photography, we capture assets that work across your website, social channels, and marketing materials.',
      'We also produce ongoing social content — the kind of regular photo and video assets that feed your social media management — and motion graphics for explainer videos, ads, and presentations.',
    ],
    deliverables: [
      { name: 'Brand Films & Corporate Videos', detail: '2–3 minute films, script to delivery, 2–4 weeks.' },
      { name: 'Corporate / Event Photography', detail: 'Professional coverage for events and corporate needs.' },
      { name: 'Product Photography', detail: 'High-quality product imagery for e-commerce and marketing.' },
      { name: 'Social Media Content Shoots', detail: 'Ongoing photo and video content for your social channels.' },
      { name: 'Podcast Production', detail: 'Recording, editing, and production for branded podcasts.' },
      { name: '2D/Motion Graphics & Animation', detail: 'Explainer videos, animated ads, and presentation graphics.' },
    ],
    pricing: [
      { label: 'Brand Film (2–3 min)', price: '₦1,000,000 – ₦5,000,000', note: '2–4 weeks' },
      { label: 'Corporate / Event Photography', price: '₦150,000 – ₦600,000', note: 'Per day' },
      { label: 'Product Photography', price: '₦200,000 – ₦1,000,000', note: '1–3 days' },
      { label: 'Social Media Content Shoot', price: '₦300,000 – ₦1,500,000', note: 'Per month' },
      { label: 'Podcast Production', price: '₦200,000 – ₦800,000', note: 'Per month' },
      { label: '2D/Motion Graphics & Animation', price: '₦500,000 – ₦3,000,000', note: '1–3 weeks' },
    ],
    whoFor: ['Brands needing launch films', 'E-commerce needing product photography', 'Companies starting a podcast'],
    resultStat: { label: 'Projects Delivered', value: '40+' },
    faqs: [
      { question: 'Do you write scripts for brand films?', answer: 'Yes, script writing is part of our brand film production process — we develop the concept and script before any shooting begins.' },
      { question: 'Can you produce content for ongoing social media needs?', answer: 'Yes, our monthly content shoot packages are designed specifically to feed an ongoing social media management programme.' },
      { question: 'What\u2019s included in event photography pricing?', answer: 'A photographer for the day, edited high-resolution images delivered within an agreed turnaround, typically 3–5 days after the event.' },
      { question: 'Do you offer video editing only, without shooting?', answer: 'In some cases yes — if you have raw footage that needs editing, we can scope that as a standalone project.' },
      { question: 'How long does motion graphics work take?', answer: 'Depending on complexity, 1–3 weeks from brief to final delivery, including revision rounds.' },
    ],
    seoTitle: 'Video & Photo Production Agency Lagos — Topton Media',
    seoDescription: 'Topton Media produces brand films, product photography, social content, podcasts, and motion graphics for brands across Nigeria. Script to delivery.',
  },
  {
    slug: 'training-workshops',
    name: 'Training & Workshops',
    category: 'TRAINING',
    pitch: 'Practical digital marketing and brand strategy training for teams, SMEs, and corporate organisations.',
    priceFrom: '₦200,000/session',
    bookingUrl: 'https://toptonmedia.com/apply',
    cardImage: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=1400&q=80',
    bullets: [
      'Digital marketing masterclasses',
      'Social media for business workshops',
      'Bespoke corporate training programmes',
    ],
    whatItIs: [
      'Not every team needs to outsource marketing entirely — sometimes what\u2019s needed is practical training that builds capability in-house. We run digital marketing masterclasses, brand strategy workshops, and bespoke corporate training for teams, SMEs, and larger organisations.',
      'Sessions are built to be practical, not theoretical — participants leave with frameworks, templates, and skills they can apply immediately. Topics range from running paid ads and social media for business, to sales enablement and brand strategy fundamentals.',
      'For larger organisations, we develop bespoke multi-day programmes tailored to specific teams and goals — whether that\u2019s upskilling a marketing department or giving a sales team the digital fluency they need to support modern customer journeys.',
    ],
    deliverables: [
      { name: 'Digital Marketing Masterclass', detail: 'Full-day session for up to 20 people, ₦500,000–₦1,500,000.' },
      { name: 'Brand Strategy Workshop', detail: 'Half or full day, ₦400,000–₦1,000,000.' },
      { name: 'Social Media for Business', detail: '3–4 hour session, ₦200,000–₦600,000.' },
      { name: 'Sales Enablement Training', detail: 'Full-day session, ₦500,000–₦1,200,000.' },
      { name: 'Bespoke Corporate Programme', detail: 'Multi-day, custom-built, ₦1,000,000–₦5,000,000.' },
    ],
    pricing: [
      { label: 'Digital Marketing Masterclass', price: '₦500,000 – ₦1,500,000', note: 'Full day, up to 20 people' },
      { label: 'Brand Strategy Workshop', price: '₦400,000 – ₦1,000,000', note: 'Half/full day' },
      { label: 'Social Media for Business', price: '₦200,000 – ₦600,000', note: '3–4 hours' },
      { label: 'Sales Enablement Training', price: '₦500,000 – ₦1,200,000', note: 'Full day' },
      { label: 'Bespoke Corporate Programme', price: '₦1,000,000 – ₦5,000,000', note: 'Multi-day, custom' },
    ],
    whoFor: ['Corporate marketing teams', 'SME founders & staff', 'Sales teams'],
    resultStat: { label: 'Teams Trained', value: '15+' },
    faqs: [
      { question: 'Where do training sessions take place?', answer: 'We can run sessions at your office, a rented venue, or virtually — depending on your team\u2019s needs and size.' },
      { question: 'Can content be customised for our industry?', answer: 'Yes, every session is tailored with examples and case studies relevant to your industry and team\u2019s current challenges.' },
      { question: 'How many people can attend a masterclass?', answer: 'Our standard masterclass pricing covers up to 20 people; larger groups can be accommodated with adjusted pricing.' },
      { question: 'Do participants receive materials afterward?', answer: 'Yes, participants receive slide decks, templates, and frameworks used during the session for future reference.' },
      { question: 'Can you build a multi-session programme?', answer: 'Yes — our bespoke corporate programmes are designed as multi-day or multi-session curricula tailored to specific learning goals.' },
    ],
    seoTitle: 'Digital Marketing Training & Workshops Lagos | Topton Media',
    seoDescription: 'Topton Media runs digital marketing masterclasses, brand strategy workshops, and social media training for teams and organisations in Lagos and Nigeria.',
  },
  {
    slug: 'africa-market-entry',
    name: 'Africa Market Entry',
    category: 'STRATEGY',
    pitch: 'For international brands entering Nigeria and West Africa — research, localisation, and full launch execution.',
    priceFrom: 'GBP 2,500',
    bookingUrl: 'https://toptonmedia.com/apply',
    cardImage: 'https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=1400&q=80',
    bullets: [
      'Market entry strategy report',
      'Brand localisation for Nigerian market',
      'Full Nigeria launch campaign management',
    ],
    whatItIs: [
      'Entering Nigeria or West Africa as an international brand comes with a learning curve — different consumer behaviour, payment habits, media landscape, and competitive dynamics than markets you may already operate in. We help international brands navigate that, from initial research through to full launch.',
      'We start with a market entry strategy report — research into your category, competitors, target audience, and the practical realities of operating in the Nigerian market. From there, we localise your brand: messaging, creative, and positioning adapted for local relevance without losing what makes your brand work globally.',
      'For brands ready to launch, we manage the full campaign — paid media, PR, and on-ground activation — giving you a single team accountable for the Nigerian market entry, rather than coordinating multiple local vendors yourself.',
    ],
    deliverables: [
      { name: 'Market Entry Strategy Report', detail: 'GBP 2,500–8,000, 3–4 weeks. Research into category, competitors, and audience.' },
      { name: 'Brand Localisation', detail: 'GBP 3,000–12,000, 4–6 weeks. Messaging and creative adapted for Nigeria.' },
      { name: 'Nigeria Launch Campaign', detail: 'GBP 5,000–25,000, 6–10 weeks. Full campaign management for launch.' },
      { name: 'Ongoing Market Management Retainer', detail: 'GBP 2,000–8,000/month. Continued management post-launch.' },
    ],
    pricing: [
      { label: 'Market Entry Strategy Report', price: 'GBP 2,500 – 8,000', note: '3–4 weeks' },
      { label: 'Brand Localisation', price: 'GBP 3,000 – 12,000', note: '4–6 weeks' },
      { label: 'Nigeria Launch Campaign', price: 'GBP 5,000 – 25,000', note: '6–10 weeks' },
      { label: 'Ongoing Market Management', price: 'GBP 2,000 – 8,000 / month' },
    ],
    whoFor: ['International consumer brands', 'B2B companies expanding into West Africa', 'Investors launching new ventures in Nigeria'],
    resultStat: { label: 'Markets Served', value: 'NG, GH, KE+' },
    faqs: [
      { question: 'Do you only work with Nigeria, or other African markets too?', answer: 'Our core focus is Nigeria, but we also support entry into Ghana, Kenya, and other West/East African markets depending on the engagement.' },
      { question: 'What does the market entry strategy report include?', answer: 'Competitive analysis, audience research, regulatory and practical considerations, and recommendations for positioning and go-to-market approach.' },
      { question: 'Can you manage the entire launch, or just provide strategy?', answer: 'Both — some clients engage us for strategy only, while others want full launch campaign management as a single accountable team.' },
      { question: 'Do you work with brands that don\u2019t yet have a Nigerian entity?', answer: 'Yes, we frequently work with international brands in the early stages of exploring the market, before formal registration is complete.' },
      { question: 'How is pricing structured for international clients?', answer: 'International engagements are typically priced in GBP, with payment terms agreed based on project scope and duration.' },
    ],
    seoTitle: 'Africa Market Entry Strategy — Topton Media',
    seoDescription: 'Topton Media helps international brands enter Nigeria and West Africa — market research, brand localisation, PR, digital marketing, and full launch campaign management.',
  },
  {
    slug: 'email-crm',
    name: 'Email & CRM Marketing',
    category: 'GROWTH MARKETING',
    pitch: 'Lifecycle marketing and automation that turns your list into a revenue channel — not just a broadcast tool.',
    priceFrom: '₦200,000/month',
    bookingUrl: 'https://toptonmedia.com/apply',
    cardImage: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1400&q=80',
    bullets: [
      'Email campaign strategy & copywriting',
      'WhatsApp & CRM automation setup',
      'Lead nurturing & retention flows',
    ],
    whatItIs: [
      'Most businesses have an email list and a CRM that are vastly underused — sitting there as a database rather than working as a revenue channel. Email and CRM marketing turns that list into an ongoing source of repeat purchases, re-engagement, and nurtured leads.',
      'We build the campaigns and automation: welcome sequences for new contacts, nurture flows for leads who aren\u2019t ready to buy yet, win-back campaigns for customers who\u2019ve gone quiet, and regular newsletters that keep your brand top of mind.',
      'For Nigerian businesses, WhatsApp is often more effective than email alone — so we build automation that works across both channels, integrated with your CRM so every contact\u2019s journey is tracked in one place.',
    ],
    deliverables: [
      { name: 'Email Campaign Strategy & Copywriting', detail: 'Ongoing campaign planning and copy written to convert.' },
      { name: 'WhatsApp & CRM Automation Setup', detail: 'One-off setup plus ongoing maintenance.' },
      { name: 'CRM Setup & Integration', detail: 'Get your CRM properly connected to your marketing tools.' },
      { name: 'Marketing Automation', detail: 'Multi-step automated flows triggered by customer behaviour.' },
      { name: 'Lead Nurturing & Retention Flows', detail: 'Keep leads warm and bring customers back.' },
    ],
    pricing: [
      { label: 'Email Marketing', price: '₦200,000 – ₦800,000 / month' },
      { label: 'WhatsApp/CRM Automation Setup', price: '₦300,000 – ₦1,500,000', note: 'One-off + maintenance' },
      { label: 'CRM Setup & Integration', price: '₦400,000 – ₦1,500,000', note: '1–2 weeks' },
      { label: 'Marketing Automation', price: '₦500,000 – ₦2,000,000', note: '2–3 weeks' },
    ],
    whoFor: ['E-commerce brands', 'Subscription & membership businesses', 'B2B companies with long sales cycles'],
    resultStat: { label: 'Repeat Purchase Rate', value: '+27%' },
    faqs: [
      { question: 'Do you work with our existing email platform?', answer: 'Yes, we work with most major platforms including Mailchimp, Klaviyo, and others — or can recommend a switch if your current setup is limiting.' },
      { question: 'What\u2019s included in WhatsApp automation?', answer: 'Automated messages triggered by customer actions — order confirmations, abandoned cart reminders, follow-ups — using approved WhatsApp business tooling.' },
      { question: 'How long does CRM setup take?', answer: 'Typically 1–2 weeks depending on the complexity of your existing data and required integrations.' },
      { question: 'Can this work alongside lead generation campaigns?', answer: 'Yes — in fact it\u2019s most effective paired with lead generation, since nurture flows are what convert captured leads into customers over time.' },
      { question: 'Do you write the email content or just set up the automation?', answer: 'Both — email copywriting is included in our email marketing service, and we can write copy for automated flows as part of setup.' },
    ],
    seoTitle: 'Email Marketing & CRM Automation Lagos | Topton Media',
    seoDescription: 'Topton Media builds email marketing systems and CRM automation for brands in Nigeria — campaign strategy, copywriting, WhatsApp automation, and lifecycle flows.',
  },
  {
    slug: 'seo',
    name: 'SEO',
    category: 'GROWTH MARKETING',
    pitch: 'Rank higher on Google and get found by the people already searching for what you sell.',
    priceFrom: '₦300,000/month (min 3 months)',
    bookingUrl: 'https://toptonmedia.com/apply',
    cardImage: 'https://images.unsplash.com/photo-1562577309-4932fdd64cd1?w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1562577309-4932fdd64cd1?w=1400&q=80',
    bullets: [
      'Technical SEO audits & fixes',
      'On-page optimisation & content strategy',
      'Link building & authority development',
    ],
    whatItIs: [
      'SEO (search engine optimisation) is how your website earns visibility on Google without paying for every click. For Nigerian brands, this means showing up when people search for what you offer — whether that\u2019s a product, a service, or a question your business can answer.',
      'We start with a technical audit — finding and fixing the issues that hold sites back from ranking: slow load times, broken links, missing metadata, poor mobile experience. From there, we build a content strategy targeting the search terms your potential customers actually use.',
      'SEO is a compounding investment — results build over months, not days, but they keep paying off long after a campaign ends. Link building and ongoing content development build the authority that helps your site rank and stay ranked.',
    ],
    deliverables: [
      { name: 'Technical SEO Audits & Fixes', detail: 'Find and fix issues holding your site back from ranking.' },
      { name: 'On-page Optimisation', detail: 'Optimise existing pages for target keywords and search intent.' },
      { name: 'Content Strategy', detail: 'A plan for content that targets what your customers search for.' },
      { name: 'Link Building & Authority Development', detail: 'Build the domain authority that helps you rank and stay ranked.' },
    ],
    pricing: [
      { label: 'SEO', price: '₦300,000 – ₦1,200,000 / month', note: 'Minimum 3-month commitment' },
    ],
    whoFor: ['B2B service businesses', 'E-commerce brands', 'Content-driven businesses'],
    resultStat: { label: 'Organic Growth', value: '+152%' },
    faqs: [
      { question: 'How long until we see SEO results?', answer: 'Most clients begin seeing measurable ranking improvements from month 2–3, with more significant traffic growth typically visible by month 4–6.' },
      { question: 'Why is there a minimum 3-month commitment?', answer: 'SEO requires consistent work over time to show results — search engines reward sustained effort, not one-off changes.' },
      { question: 'Do you write the content too?', answer: 'Yes, content strategy and creation can be included, or we can work alongside your existing content team with optimisation guidance.' },
      { question: 'What does a technical SEO audit cover?', answer: 'Site speed, mobile usability, indexing issues, site structure, metadata, and any technical barriers preventing search engines from properly crawling your site.' },
      { question: 'Is SEO worth it for a small local business?', answer: 'Yes — local SEO in particular can be highly effective for service businesses, helping you show up when nearby customers search for what you offer.' },
    ],
    seoTitle: 'SEO Agency Lagos | Nigerian Brands — Topton Media',
    seoDescription: 'Topton Media provides technical SEO, content strategy, and link building for brands in Nigeria and across Africa. Results visible from month 2–3.',
    featuredOnHome: true,
  },
]

export function getServiceBySlug(slug: string): ServiceData | undefined {
  return SERVICES.find(s => s.slug === slug)
}

export const SERVICE_CATEGORIES = [
  'All',
  'Growth Marketing',
  'Tech & Web',
  'Brand & Creative',
  'Production',
  'Printing',
  'Gifting',
  'PR & Comms',
  'Activations',
  'Training',
  'Strategy',
] as const