/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as MarketingAgencyNigeriaRouteImport } from './routes/marketing-agency-nigeria'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as B2bLeadGenerationAgencyInNigeriaRouteImport } from './routes/b2b-lead-generation-agency-in-nigeria'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AdvertisingCompanyLagosRouteImport } from './routes/advertising-company-lagos'
import { Route as AdvertisingAgencyLagosRouteImport } from './routes/advertising-agency-lagos'
import { Route as AdvertisingAgenciesInIkejaRouteImport } from './routes/advertising-agencies-in-ikeja'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ShopSlugRouteImport } from './routes/shop/$slug'
import { Route as ServicesSlugRouteImport } from './routes/services/$slug'
import { Route as OrderConfirmationRouteImport } from './routes/order/confirmation'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as AdminBlogNewRouteImport } from './routes/admin/blog/new'
import { Route as AdminBlogIdRouteImport } from './routes/admin/blog/$id'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingAgencyNigeriaRoute = MarketingAgencyNigeriaRouteImport.update({
  id: '/marketing-agency-nigeria',
  path: '/marketing-agency-nigeria',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const B2bLeadGenerationAgencyInNigeriaRoute =
  B2bLeadGenerationAgencyInNigeriaRouteImport.update({
    id: '/b2b-lead-generation-agency-in-nigeria',
    path: '/b2b-lead-generation-agency-in-nigeria',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertisingCompanyLagosRoute = AdvertisingCompanyLagosRouteImport.update({
  id: '/advertising-company-lagos',
  path: '/advertising-company-lagos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertisingAgencyLagosRoute = AdvertisingAgencyLagosRouteImport.update({
  id: '/advertising-agency-lagos',
  path: '/advertising-agency-lagos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertisingAgenciesInIkejaRoute =
  AdvertisingAgenciesInIkejaRouteImport.update({
    id: '/advertising-agencies-in-ikeja',
    path: '/advertising-agencies-in-ikeja',
    getParentRoute: () => rootRouteImport,
  } as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/shop/$slug',
  path: '/shop/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesRoute,
} as any)
const OrderConfirmationRoute = OrderConfirmationRouteImport.update({
  id: '/order/confirmation',
  path: '/order/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AdminBlogNewRoute = AdminBlogNewRouteImport.update({
  id: '/admin/blog/new',
  path: '/admin/blog/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogIdRoute = AdminBlogIdRouteImport.update({
  id: '/admin/blog/$id',
  path: '/admin/blog/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advertising-agencies-in-ikeja': typeof AdvertisingAgenciesInIkejaRoute
  '/advertising-agency-lagos': typeof AdvertisingAgencyLagosRoute
  '/advertising-company-lagos': typeof AdvertisingCompanyLagosRoute
  '/apply': typeof ApplyRoute
  '/b2b-lead-generation-agency-in-nigeria': typeof B2bLeadGenerationAgencyInNigeriaRoute
  '/blog': typeof BlogRouteWithChildren
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/marketing-agency-nigeria': typeof MarketingAgencyNigeriaRoute
  '/services': typeof ServicesRouteWithChildren
  '/team': typeof TeamRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/order/confirmation': typeof OrderConfirmationRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advertising-agencies-in-ikeja': typeof AdvertisingAgenciesInIkejaRoute
  '/advertising-agency-lagos': typeof AdvertisingAgencyLagosRoute
  '/advertising-company-lagos': typeof AdvertisingCompanyLagosRoute
  '/apply': typeof ApplyRoute
  '/b2b-lead-generation-agency-in-nigeria': typeof B2bLeadGenerationAgencyInNigeriaRoute
  '/blog': typeof BlogRouteWithChildren
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/marketing-agency-nigeria': typeof MarketingAgencyNigeriaRoute
  '/services': typeof ServicesRouteWithChildren
  '/team': typeof TeamRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/order/confirmation': typeof OrderConfirmationRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/admin': typeof AdminIndexRoute
  '/shop': typeof ShopIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advertising-agencies-in-ikeja': typeof AdvertisingAgenciesInIkejaRoute
  '/advertising-agency-lagos': typeof AdvertisingAgencyLagosRoute
  '/advertising-company-lagos': typeof AdvertisingCompanyLagosRoute
  '/apply': typeof ApplyRoute
  '/b2b-lead-generation-agency-in-nigeria': typeof B2bLeadGenerationAgencyInNigeriaRoute
  '/blog': typeof BlogRouteWithChildren
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/marketing-agency-nigeria': typeof MarketingAgencyNigeriaRoute
  '/services': typeof ServicesRouteWithChildren
  '/team': typeof TeamRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/order/confirmation': typeof OrderConfirmationRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/advertising-agencies-in-ikeja'
    | '/advertising-agency-lagos'
    | '/advertising-company-lagos'
    | '/apply'
    | '/b2b-lead-generation-agency-in-nigeria'
    | '/blog'
    | '/case-studies'
    | '/contact'
    | '/marketing-agency-nigeria'
    | '/services'
    | '/team'
    | '/blog/$slug'
    | '/order/confirmation'
    | '/services/$slug'
    | '/shop/$slug'
    | '/admin/'
    | '/shop/'
    | '/admin/blog/$id'
    | '/admin/blog/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/advertising-agencies-in-ikeja'
    | '/advertising-agency-lagos'
    | '/advertising-company-lagos'
    | '/apply'
    | '/b2b-lead-generation-agency-in-nigeria'
    | '/blog'
    | '/case-studies'
    | '/contact'
    | '/marketing-agency-nigeria'
    | '/services'
    | '/team'
    | '/blog/$slug'
    | '/order/confirmation'
    | '/services/$slug'
    | '/shop/$slug'
    | '/admin'
    | '/shop'
    | '/admin/blog/$id'
    | '/admin/blog/new'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/advertising-agencies-in-ikeja'
    | '/advertising-agency-lagos'
    | '/advertising-company-lagos'
    | '/apply'
    | '/b2b-lead-generation-agency-in-nigeria'
    | '/blog'
    | '/case-studies'
    | '/contact'
    | '/marketing-agency-nigeria'
    | '/services'
    | '/team'
    | '/blog/$slug'
    | '/order/confirmation'
    | '/services/$slug'
    | '/shop/$slug'
    | '/admin/'
    | '/shop/'
    | '/admin/blog/$id'
    | '/admin/blog/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdvertisingAgenciesInIkejaRoute: typeof AdvertisingAgenciesInIkejaRoute
  AdvertisingAgencyLagosRoute: typeof AdvertisingAgencyLagosRoute
  AdvertisingCompanyLagosRoute: typeof AdvertisingCompanyLagosRoute
  ApplyRoute: typeof ApplyRoute
  B2bLeadGenerationAgencyInNigeriaRoute: typeof B2bLeadGenerationAgencyInNigeriaRoute
  BlogRoute: typeof BlogRouteWithChildren
  CaseStudiesRoute: typeof CaseStudiesRoute
  ContactRoute: typeof ContactRoute
  MarketingAgencyNigeriaRoute: typeof MarketingAgencyNigeriaRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  TeamRoute: typeof TeamRoute
  OrderConfirmationRoute: typeof OrderConfirmationRoute
  ShopSlugRoute: typeof ShopSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ShopIndexRoute: typeof ShopIndexRoute
  AdminBlogIdRoute: typeof AdminBlogIdRoute
  AdminBlogNewRoute: typeof AdminBlogNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing-agency-nigeria': {
      id: '/marketing-agency-nigeria'
      path: '/marketing-agency-nigeria'
      fullPath: '/marketing-agency-nigeria'
      preLoaderRoute: typeof MarketingAgencyNigeriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b2b-lead-generation-agency-in-nigeria': {
      id: '/b2b-lead-generation-agency-in-nigeria'
      path: '/b2b-lead-generation-agency-in-nigeria'
      fullPath: '/b2b-lead-generation-agency-in-nigeria'
      preLoaderRoute: typeof B2bLeadGenerationAgencyInNigeriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advertising-company-lagos': {
      id: '/advertising-company-lagos'
      path: '/advertising-company-lagos'
      fullPath: '/advertising-company-lagos'
      preLoaderRoute: typeof AdvertisingCompanyLagosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advertising-agency-lagos': {
      id: '/advertising-agency-lagos'
      path: '/advertising-agency-lagos'
      fullPath: '/advertising-agency-lagos'
      preLoaderRoute: typeof AdvertisingAgencyLagosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advertising-agencies-in-ikeja': {
      id: '/advertising-agencies-in-ikeja'
      path: '/advertising-agencies-in-ikeja'
      fullPath: '/advertising-agencies-in-ikeja'
      preLoaderRoute: typeof AdvertisingAgenciesInIkejaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/shop/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/order/confirmation': {
      id: '/order/confirmation'
      path: '/order/confirmation'
      fullPath: '/order/confirmation'
      preLoaderRoute: typeof OrderConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/admin/blog/new': {
      id: '/admin/blog/new'
      path: '/admin/blog/new'
      fullPath: '/admin/blog/new'
      preLoaderRoute: typeof AdminBlogNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog/$id': {
      id: '/admin/blog/$id'
      path: '/admin/blog/$id'
      fullPath: '/admin/blog/$id'
      preLoaderRoute: typeof AdminBlogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface ServicesRouteChildren {
  ServicesSlugRoute: typeof ServicesSlugRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesSlugRoute: ServicesSlugRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdvertisingAgenciesInIkejaRoute: AdvertisingAgenciesInIkejaRoute,
  AdvertisingAgencyLagosRoute: AdvertisingAgencyLagosRoute,
  AdvertisingCompanyLagosRoute: AdvertisingCompanyLagosRoute,
  ApplyRoute: ApplyRoute,
  B2bLeadGenerationAgencyInNigeriaRoute: B2bLeadGenerationAgencyInNigeriaRoute,
  BlogRoute: BlogRouteWithChildren,
  CaseStudiesRoute: CaseStudiesRoute,
  ContactRoute: ContactRoute,
  MarketingAgencyNigeriaRoute: MarketingAgencyNigeriaRoute,
  ServicesRoute: ServicesRouteWithChildren,
  TeamRoute: TeamRoute,
  OrderConfirmationRoute: OrderConfirmationRoute,
  ShopSlugRoute: ShopSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  ShopIndexRoute: ShopIndexRoute,
  AdminBlogIdRoute: AdminBlogIdRoute,
  AdminBlogNewRoute: AdminBlogNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
